
  A2 = [botwinklbl_disc2_res_4_irred.t_exp.prc_mean([1,2]); ...
  botwinklbl_disc2_res_4_irred.tb_exp.prc_mean([1,2]); ...
  botwinklbl_disc2_res_4_irred.mt_exp.prc_mean([1,2]); ...
  botwinklbl_disc2_res_4_irred.amt_exp.prc_mean([1,2]); ...
  botwinklbl_disc2_res_4_irred.mtb_exp.prc_mean([1,2]); ...
  botwinklbl_disc2_res_4_irred.amtb_exp.prc_mean([1,2]); ...
  botwinklbl_disc2_res_4_irred.mgat_exp.prc_mean([1,2]); ... 
  botwinklbl_disc2_res_4_irred.amgat_exp.prc_mean([1,2]); ... 
  botwinklbl_disc2_res_4_irred.mgatb_exp.prc_mean([1,2]); ... 
  botwinklbl_disc2_res_4_irred.amgatb_exp.prc_mean([1,2])] / 100;
  
  B2 = [botwinklbl_disc2_res_4_irred.t_exp.time_mean; ...  
  botwinklbl_disc2_res_4_irred.tb_exp.time_mean; ...
  botwinklbl_disc2_res_4_irred.mt_exp.time_mean; ...
  botwinklbl_disc2_res_4_irred.amt_exp.time_mean; ...
  botwinklbl_disc2_res_4_irred.mtb_exp.time_mean; ...
  botwinklbl_disc2_res_4_irred.amtb_exp.time_mean; ...
  botwinklbl_disc2_res_4_irred.mgat_exp.time_mean; ... 
  botwinklbl_disc2_res_4_irred.amgat_exp.time_mean; ... 
  botwinklbl_disc2_res_4_irred.mgatb_exp.time_mean; ... 
  botwinklbl_disc2_res_4_irred.amgatb_exp.time_mean];

C2 = [A2,B2]
  
 A = [botwinklbl_disc2_res_3_irred.t_exp.prc_mean([1,2]); ...
  botwinklbl_disc2_res_3_irred.tb_exp.prc_mean([1,2]); ...
  botwinklbl_disc2_res_3_irred.mt_exp.prc_mean([1,2]); ...
  botwinklbl_disc2_res_3_irred.amt_exp.prc_mean([1,2]); ...
  botwinklbl_disc2_res_3_irred.mtb_exp.prc_mean([1,2]); ...
  botwinklbl_disc2_res_3_irred.amtb_exp.prc_mean([1,2]); ...
  botwinklbl_disc2_res_3_irred.mgat_exp.prc_mean([1,2]); ... 
  botwinklbl_disc2_res_3_irred.amgat_exp.prc_mean([1,2]); ... 
  botwinklbl_disc2_res_3_irred.mgatb_exp.prc_mean([1,2]); ... 
  botwinklbl_disc2_res_3_irred.amgatb_exp.prc_mean([1,2])] / 100;
  
  B = [botwinklbl_disc2_res_3_irred.t_exp.time_mean; ...  
  botwinklbl_disc2_res_3_irred.tb_exp.time_mean; ...
  botwinklbl_disc2_res_3_irred.mt_exp.time_mean; ...
  botwinklbl_disc2_res_3_irred.amt_exp.time_mean; ...
  botwinklbl_disc2_res_3_irred.mtb_exp.time_mean; ...
  botwinklbl_disc2_res_3_irred.amtb_exp.time_mean; ...
  botwinklbl_disc2_res_3_irred.mgat_exp.time_mean; ... 
  botwinklbl_disc2_res_3_irred.amgat_exp.time_mean; ... 
  botwinklbl_disc2_res_3_irred.mgatb_exp.time_mean; ... 
  botwinklbl_disc2_res_3_irred.amgatb_exp.time_mean];

C = [A,B]
C_all = reshape([C, C2]', 3, 20)';
ExportToExcel(C_all);


  [botwinklbl_disc2_res_4_irred.mga_exp.prc_mean([1,2]);...
  botwinklbl_disc2_res_4_irred.amga_exp.prc_mean([1,2])] / 100
 
  [botwinklbl_disc2_res_4_irred.mga_exp.time_mean; ... 
  botwinklbl_disc2_res_4_irred.amga_exp.time_mean]

  used_algs = [true, false(1,11), true, true];
  manelis3_res_3_irred = LOOcv('..\Data\All\manelis3.txt', used_algs, 3);
  used_algs(end-1:end) = false;
  
  used_algs = [true(1,12) false(1,4)];
  botwinklbl_disc2_res_4_irred = LOOcv('..\Data\Discretized\TLMEL_disc2.tab', used_algs, 4);
  used_algs = [true(1,10) false(1,6)];
  botwinklbl_disc2_res_3_irred = LOOcv('..\Data\Discretized\TLMEL_disc2.tab', used_algs, 3);

  used_algs = [true(1,12) false(1,4)];
  botwinklbl_disc2_res_4_irred = LOOcv('..\Data\Discretized\Pnevmo_r_disc2.tab', used_algs, 4);
  used_algs = [true(1,10) false(1,6)];
  botwinklbl_disc2_res_3_irred = LOOcv('..\Data\Discretized\Pnevmo_r_disc2.tab', used_algs, 3);

 
 