
  A2 = [sarcoma_disc2_res_4_irred.t_exp.prc_mean([1,2]); ...
  sarcoma_disc2_res_4_irred.tb_exp.prc_mean([1,2]); ...
  sarcoma_disc2_res_4_irred.mt_exp.prc_mean([1,2]); ...
  sarcoma_disc2_res_4_irred.amt_exp.prc_mean([1,2]); ...
  sarcoma_disc2_res_4_irred.mtb_exp.prc_mean([1,2]); ...
  sarcoma_disc2_res_4_irred.amtb_exp.prc_mean([1,2]); ...
  sarcoma_disc2_res_4_irred.mgat_exp.prc_mean([1,2]); ... 
  sarcoma_disc2_res_4_irred.amgat_exp.prc_mean([1,2]); ... 
  sarcoma_disc2_res_4_irred.mgatb_exp.prc_mean([1,2]); ... 
  sarcoma_disc2_res_4_irred.amgatb_exp.prc_mean([1,2])] / 100;
  
  B2 = [sarcoma_disc2_res_4_irred.t_exp.time_mean; ...  
  sarcoma_disc2_res_4_irred.tb_exp.time_mean; ...
  sarcoma_disc2_res_4_irred.mt_exp.time_mean; ...
  sarcoma_disc2_res_4_irred.amt_exp.time_mean; ...
  sarcoma_disc2_res_4_irred.mtb_exp.time_mean; ...
  sarcoma_disc2_res_4_irred.amtb_exp.time_mean; ...
  sarcoma_disc2_res_4_irred.mgat_exp.time_mean; ... 
  sarcoma_disc2_res_4_irred.amgat_exp.time_mean; ... 
  sarcoma_disc2_res_4_irred.mgatb_exp.time_mean; ... 
  sarcoma_disc2_res_4_irred.amgatb_exp.time_mean];

C2 = [A2,B2];
  
 A = [sarcoma_disc2_res_3_irred.t_exp.prc_mean([1,2]); ...
  sarcoma_disc2_res_3_irred.tb_exp.prc_mean([1,2]); ...
  sarcoma_disc2_res_3_irred.mt_exp.prc_mean([1,2]); ...
  sarcoma_disc2_res_3_irred.amt_exp.prc_mean([1,2]); ...
  sarcoma_disc2_res_3_irred.mtb_exp.prc_mean([1,2]); ...
  sarcoma_disc2_res_3_irred.amtb_exp.prc_mean([1,2]); ...
  sarcoma_disc2_res_3_irred.mgat_exp.prc_mean([1,2]); ... 
  sarcoma_disc2_res_3_irred.amgat_exp.prc_mean([1,2]); ... 
  sarcoma_disc2_res_3_irred.mgatb_exp.prc_mean([1,2]); ... 
  sarcoma_disc2_res_3_irred.amgatb_exp.prc_mean([1,2])] / 100;
  
  B = [sarcoma_disc2_res_3_irred.t_exp.time_mean; ...  
  sarcoma_disc2_res_3_irred.tb_exp.time_mean; ...
  sarcoma_disc2_res_3_irred.mt_exp.time_mean; ...
  sarcoma_disc2_res_3_irred.amt_exp.time_mean; ...
  sarcoma_disc2_res_3_irred.mtb_exp.time_mean; ...
  sarcoma_disc2_res_3_irred.amtb_exp.time_mean; ...
  sarcoma_disc2_res_3_irred.mgat_exp.time_mean; ... 
  sarcoma_disc2_res_3_irred.amgat_exp.time_mean; ... 
  sarcoma_disc2_res_3_irred.mgatb_exp.time_mean; ... 
  sarcoma_disc2_res_3_irred.amgatb_exp.time_mean];

C = [A,B];
C_all = reshape([C, C2]', 3, 20)';
ExportToExcel(C_all);


  [sarcoma_disc2_res_4_irred.mga_exp.prc_mean([1,2]);...
  sarcoma_disc2_res_4_irred.amga_exp.prc_mean([1,2])] / 100
 
  [sarcoma_disc2_res_4_irred.mga_exp.time_mean; ... 
  sarcoma_disc2_res_4_irred.amga_exp.time_mean]